/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScansIndexRouteImport } from './routes/scans.index'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as ScansDiffRouteImport } from './routes/scans.diff'
import { Route as ScansIdRouteImport } from './routes/scans.$id'
import { Route as ScanNewRouteImport } from './routes/scan.new'
import { Route as FleetIdRouteImport } from './routes/fleet.$id'
import { Route as ScansLiveIdRouteImport } from './routes/scans.live.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIndexRoute = ScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansDiffRoute = ScansDiffRouteImport.update({
  id: '/scans/diff',
  path: '/scans/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIdRoute = ScansIdRouteImport.update({
  id: '/scans/$id',
  path: '/scans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanNewRoute = ScanNewRouteImport.update({
  id: '/scan/new',
  path: '/scan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIdRoute = FleetIdRouteImport.update({
  id: '/fleet/$id',
  path: '/fleet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansLiveIdRoute = ScansLiveIdRouteImport.update({
  id: '/scans/live/$id',
  path: '/scans/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/settings': typeof SettingsRoute
  '/fleet/$id': typeof FleetIdRoute
  '/scan/new': typeof ScanNewRoute
  '/scans/$id': typeof ScansIdRoute
  '/scans/diff': typeof ScansDiffRoute
  '/fleet/': typeof FleetIndexRoute
  '/scans/': typeof ScansIndexRoute
  '/scans/live/$id': typeof ScansLiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/settings': typeof SettingsRoute
  '/fleet/$id': typeof FleetIdRoute
  '/scan/new': typeof ScanNewRoute
  '/scans/$id': typeof ScansIdRoute
  '/scans/diff': typeof ScansDiffRoute
  '/fleet': typeof FleetIndexRoute
  '/scans': typeof ScansIndexRoute
  '/scans/live/$id': typeof ScansLiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/settings': typeof SettingsRoute
  '/fleet/$id': typeof FleetIdRoute
  '/scan/new': typeof ScanNewRoute
  '/scans/$id': typeof ScansIdRoute
  '/scans/diff': typeof ScansDiffRoute
  '/fleet/': typeof FleetIndexRoute
  '/scans/': typeof ScansIndexRoute
  '/scans/live/$id': typeof ScansLiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/history'
    | '/inventory'
    | '/settings'
    | '/fleet/$id'
    | '/scan/new'
    | '/scans/$id'
    | '/scans/diff'
    | '/fleet/'
    | '/scans/'
    | '/scans/live/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/history'
    | '/inventory'
    | '/settings'
    | '/fleet/$id'
    | '/scan/new'
    | '/scans/$id'
    | '/scans/diff'
    | '/fleet'
    | '/scans'
    | '/scans/live/$id'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/history'
    | '/inventory'
    | '/settings'
    | '/fleet/$id'
    | '/scan/new'
    | '/scans/$id'
    | '/scans/diff'
    | '/fleet/'
    | '/scans/'
    | '/scans/live/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  SettingsRoute: typeof SettingsRoute
  FleetIdRoute: typeof FleetIdRoute
  ScanNewRoute: typeof ScanNewRoute
  ScansIdRoute: typeof ScansIdRoute
  ScansDiffRoute: typeof ScansDiffRoute
  FleetIndexRoute: typeof FleetIndexRoute
  ScansIndexRoute: typeof ScansIndexRoute
  ScansLiveIdRoute: typeof ScansLiveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/': {
      id: '/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof ScansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/diff': {
      id: '/scans/diff'
      path: '/scans/diff'
      fullPath: '/scans/diff'
      preLoaderRoute: typeof ScansDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$id': {
      id: '/scans/$id'
      path: '/scans/$id'
      fullPath: '/scans/$id'
      preLoaderRoute: typeof ScansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/new': {
      id: '/scan/new'
      path: '/scan/new'
      fullPath: '/scan/new'
      preLoaderRoute: typeof ScanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$id': {
      id: '/fleet/$id'
      path: '/fleet/$id'
      fullPath: '/fleet/$id'
      preLoaderRoute: typeof FleetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/live/$id': {
      id: '/scans/live/$id'
      path: '/scans/live/$id'
      fullPath: '/scans/live/$id'
      preLoaderRoute: typeof ScansLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  SettingsRoute: SettingsRoute,
  FleetIdRoute: FleetIdRoute,
  ScanNewRoute: ScanNewRoute,
  ScansIdRoute: ScansIdRoute,
  ScansDiffRoute: ScansDiffRoute,
  FleetIndexRoute: FleetIndexRoute,
  ScansIndexRoute: ScansIndexRoute,
  ScansLiveIdRoute: ScansLiveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
